**Name: Kshitij Amitkumar Mondal<br>
Roll No: TCOD-73<br>
Class: TE-D<br>
Batch: T12**

# Assignment No: 6
Title of the Assignment:
1. Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv
dataset.
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision,
Recall on the given dataset.

Import libraries and create alias for Pandas, Numpy and Matplotlib

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Import the Iris dataset by calling URL.

In [ ]:
df = pd.read_csv("/content/iris.csv")

In [ ]:
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica


In [ ]:
df.isnull().sum()

,0
sepal_length,0
sepal_width,0
petal_length,0
petal_width,0
species,0


Converting Categorical to Numerical Values (Label Encoding)

In [ ]:
from sklearn import preprocessing

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
label_encoder = preprocessing.LabelEncoder()

In [ ]:
df['species']= label_encoder.fit_transform(df['species'])

In [ ]:
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [ ]:
x = df.drop(['species'], axis = 1)
y = df['species']

In [ ]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size =0.2,random_state = 0)

#Gaussian Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
gaussian = GaussianNB()
gaussian.fit(xtrain, ytrain)

GaussianNB()

In [ ]:
ytrain_pred = gaussian.predict(xtrain)
ytest_pred = gaussian.predict(xtest)

In [ ]:
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score,
    f1_score, confusion_matrix, classification_report
)

Accuracy Score

In [ ]:
print(accuracy_score(ytrain, ytrain_pred))

0.95


In [ ]:
print(accuracy_score(ytest, ytest_pred))

0.9666666666666667


Error Rate

In [ ]:
print(1-accuracy_score(ytrain, ytrain_pred))

0.050000000000000044


In [ ]:
print(1-accuracy_score(ytest, ytest_pred))

0.033333333333333326


Precision Score

In [ ]:
precision_score(ytrain, ytrain_pred,average='micro')

0.95

In [ ]:
precision_score(ytest, ytest_pred,average='micro')

0.9666666666666667

Recall Score

In [ ]:
recall_score(ytrain, ytrain_pred,average='micro')

0.95

In [ ]:
recall_score(ytest, ytest_pred,average='micro')

0.9666666666666667

Classification Report

In [ ]:
print(classification_report(ytrain, ytrain_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        39
           1       0.92      0.92      0.92        37
           2       0.93      0.93      0.93        44

    accuracy                           0.95       120
   macro avg       0.95      0.95      0.95       120
weighted avg       0.95      0.95      0.95       120



In [ ]:
print(classification_report(ytest, ytest_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.93      1.00      0.96        13
           2       1.00      0.83      0.91         6

    accuracy                           0.97        30
   macro avg       0.98      0.94      0.96        30
weighted avg       0.97      0.97      0.97        30



Confusion Matrix

In [ ]:
print(confusion_matrix(ytrain, ytrain_pred))

[[39  0  0]
 [ 0 34  3]
 [ 0  3 41]]


In [ ]:
print(confusion_matrix(ytest, ytest_pred))

[[11  0  0]
 [ 0 13  0]
 [ 0  1  5]]


F1 Score

In [ ]:
f1_score(ytrain, ytrain_pred, average="micro")

0.95

In [ ]:
f1_score(ytest, ytest_pred,average='micro')

0.9666666666666667

# Bernoulli Naive Bayes

In [ ]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(xtrain, ytrain)

BernoulliNB()

In [ ]:
ytrain_pred = clf.predict(xtrain)
ytest_pred = clf.predict(xtest)

Accuracy Score

In [ ]:
print(accuracy_score(ytrain, ytrain_pred))

0.36666666666666664


In [ ]:
print(accuracy_score(ytest, ytest_pred))

0.2


Error Rate

In [ ]:
print(1-accuracy_score(ytrain, ytrain_pred))

0.6333333333333333


In [ ]:
print(1-accuracy_score(ytest, ytest_pred))

0.8


Precision Score

In [ ]:
precision_score(ytrain, ytrain_pred,average='micro')

0.36666666666666664

In [ ]:
precision_score(ytest, ytest_pred,average='micro')

0.2

Recall Score

In [ ]:
recall_score(ytrain, ytrain_pred,average='micro')

0.36666666666666664

In [ ]:
recall_score(ytest, ytest_pred,average='micro')

0.2

Classification Report

In [ ]:
print(classification_report(ytrain, ytrain_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        39
           1       0.00      0.00      0.00        37
           2       0.37      1.00      0.54        44

    accuracy                           0.37       120
   macro avg       0.12      0.33      0.18       120
weighted avg       0.13      0.37      0.20       120



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
print(classification_report(ytest, ytest_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           1       0.00      0.00      0.00        13
           2       0.20      1.00      0.33         6

    accuracy                           0.20        30
   macro avg       0.07      0.33      0.11        30
weighted avg       0.04      0.20      0.07        30



/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix

In [ ]:
print(confusion_matrix(ytrain, ytrain_pred))

[[ 0  0 39]
 [ 0  0 37]
 [ 0  0 44]]


In [ ]:
print(confusion_matrix(ytest, ytest_pred))

[[ 0  0 11]
 [ 0  0 13]
 [ 0  0  6]]


F1 Score

In [ ]:
recall_score(ytrain, ytrain_pred,average='micro')

0.36666666666666664

In [ ]:
recall_score(ytest, ytest_pred,average='micro')

0.2

Conclusion:<br>
In this way we have done data analysis using Naive Bayes Algorithm for Iris dataset and
evaluated the performance of the model.

Conclusion:<br>
In this way we have done data analysis using Naive Bayes Algorithm for Iris dataset and
evaluated the performance of the model.

Conclusion:<br>
In this way we have done data analysis using Naive Bayes Algorithm for Iris dataset and
evaluated the performance of the model.

Conclusion:<br>
In this way we have done data analysis using Naive Bayes Algorithm for Iris dataset and
evaluated the performance of the model.

Execution with Formulas


Accuracy

In [ ]:
accuracy_train = np.sum(ytrain == ytrain_pred) / len(ytrain)
print(accuracy_train)

0.36666666666666664


In [ ]:
accuracy_test = np.sum(ytest == ytest_pred) / len(ytest)
print(accuracy_test)

0.2


Error Rate

In [ ]:
error_train = 1 - (np.sum(ytrain == ytrain_pred) / len(ytrain))
print(error_train)

0.6333333333333333


In [ ]:
error_test = 1 - (np.sum(ytest == ytest_pred) / len(ytest))
print(error_test)

0.8


Precision

In [ ]:
tp = np.sum(ytrain == ytrain_pred)
fp = len(ytrain) - tp
precision_train = tp / (tp + fp)
print(precision_train)

0.36666666666666664


In [ ]:
tp = np.sum(ytest == ytest_pred)
fp = len(ytest) - tp
precision_test = tp / (tp + fp)
print(precision_test)

0.2


Recall

In [ ]:
tp = np.sum(ytrain == ytrain_pred)
fn = len(ytrain) - tp
recall_train = tp / (tp + fn)
print(recall_train)

0.36666666666666664


In [ ]:
tp = np.sum(ytest == ytest_pred)
fn = len(ytest) - tp
recall_test = tp / (tp + fn)
print(recall_test)

0.2


F1 Score

In [ ]:
tp = np.sum(ytrain == ytrain_pred)
fp = len(ytrain) - tp
fn = len(ytrain) - tp
f1_train = (2 * tp) / (2 * tp + fp + fn)
print(f1_train)

0.36666666666666664


In [ ]:
tp = np.sum(ytest == ytest_pred)
fp = len(ytest) - tp
fn = len(ytest) - tp
f1_test = (2 * tp) / (2 * tp + fp + fn)
print(f1_test)

0.2
